Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.network "33.33.33.12"

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "init.pp"
    puppet.module_path = "modules"
  end
end
